### ISSUE TITLE
Missing pixels in Planck half-mission are being ignored and treated as zeros

### ISSUE THREAD

**Issue by msyriac** [ACTCollaboration/tilec#15]
We should switch to ring splits. This is high priority.

**Comment by jcolinhill** [comment]
why are there missing pixels in the HM splits?  in a single "season" (year), it's true that the whole sky isn't observed, but in 2 seasons, it is

**Comment by jcolinhill** [comment]
are these just a few isolated empty pixels?

**Comment by msyriac** [comment]
Yes, it's less than a percent of pixels in Deep6 for example.

**Comment by jcolinhill** [comment]
are you sure the HR splits won't have the same problem?

**Comment by msyriac** [comment]
I've checked explicitly for 143 GHz (which did have missing pixels for half mission). When all the half rings are reprojected today, I'll check this for all of the frequencies.

**Comment by jcolinhill** [comment]
do the missing pixels have "UNSEEN" values?  (the healpix flag value)

**Comment by msyriac** [comment]
Yep, certainly in the inverse variance maps (Sigurd checked this). Not sure about in the actual split maps. Now that I think of it, I'm not sure if these pixels are being treated as zeros or as large negative values. Need to check.

**Comment by msyriac** [comment]
Ah -- what happens is that the missing pixels end up having zero inverse variance in Sigurd's reprojected maps. So no large negative numbers there. Need to check what the reprojected splits actually have.

**Comment by jcolinhill** [comment]
I suspect that changing this will have ~zero impact on the results
